testAPI=()=>{
    $.ajax({
        //url:'http://imy.up.ac.za/IMY220/u17074292/API.php',
        url:"http://localhost/IMY220_Project/API.php",
        type:'GET',
        cache:false,
        data:{
            'gaImages':0,
        },
        success:(res)=>{
            console.log(res);
        },
        error:(e)=>{
            console.log(e);
        }
    })
}

(()=>{
    testAPI();
})()
